### PR TITLE
Added stryker mutator package as a tool for mutation testing.

### PR DESCRIPTION
**Pull request by Procos12**
The reason stryker-mutator was chosen for our project because it was straightforward to setup, and can test varied inputs for our project for both the anonymous and search features, as well as testing other functions in our repository to check for code quality.

Installation is as such:

npm init stryker
None
Mocha
Mocha
HTML
Javascript

stryker-mutator-output.txt contains output after running npx stryker run --fileLogLevel trace --logLevel debug

### CODE REVIEW

**Comment by Procos12** [comment]
Forgot to add, but installation is as such:

npm init stryker
None
Mocha
Mocha
HTML
Javascript

**Review by aalman3 — COMMENTED** [review]
Make sure to include a screenshot of the output from the terminal if there is one, otherwise this looks good

**Comment by Procos12** [comment]
output is included in stryker-mutator-output.txt at the root-level folder

The reason stryker-mutator was chosen for our project because it was straightforward to setup, and can test varied inputs for our project for both the anonymous and search features, as well as testing other functions in our repository to check for code quality.

**Comment by Procos12** [comment]
We decided against using the tool.

**Pull request merged**
